<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TerrestreSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        
        DB::table('terrestre')->insert([
        'Voucher' => str_random(10),
        'DtFaturam' => '2018-08-21',
        'DtEmissao' => '2018-08-21',
        'Fil' => str_random(10),
        'Filial' => str_random(10),
        'Ems' => str_random(10),
        'Emissor' => str_random(10),
        'FaturaCli' => str_random(10),
        'FaturaFor' => str_random(10),
        'DocCliente' => str_random(10),
        'NomePax' => str_random(10),
        'DtEntrada' => '2018-08-21',
        'DtSaida' => '2018-08-21',
        'Contato' => str_random(10),
        'Descricao_CCusto' => str_random(10),
        'Depto' => str_random(10),
        'TpVch' => str_random(10),
        'FormaPgto' => rand(0,100),
        'TpFat' => rand(0,100),
        'TpFatForn' => rand(0,100),
        'Produto' => str_random(10),
        'DescricaoProduto' => str_random(10),
        'M' => rand(0,100),
        'Moeda' => str_random(10),
        'DtConversao' => str_random(10),
        'MFor' => rand(0,100),
        'MoedaFor' => str_random(10),
        'DtConversaoPgto' => str_random(10),
        'DtVenctoCli' => '2018-08-21',
        'DtVenctoFor' => str_random(10),
        'DtVenctoSinalFor' => str_random(10),
        'Categ' => str_random(10),
        'Cliente' => str_random(10),
        'TpCli' => str_random(10),
        'GrupoCli' => str_random(10),
        'CidadeCli' => str_random(10),
        'MunicipioCli' => str_random(10),
        'UFCli' => str_random(10),
        'EstadoCli' => str_random(10),
        'Fornecedor' => str_random(10),
        'TpFor' => str_random(10),
        'GrupoFor' => str_random(10),
        'CidadeFor' => str_random(10),
        'MunicipioFor' => str_random(10),
        'UFFor' => str_random(10),
        'EstadorFor' => str_random(10),
        'Operadora' => str_random(10),
        'TpOper' => str_random(10),
        'GrupoOper' => str_random(10),
        'CidadeOper' => str_random(10),
        'MunicipioOper' => str_random(10),
        'UFOper' => str_random(10),
        'EstadoOper' => str_random(10),
        'NroPax' => rand(0,100),
        'CambioCli' => rand(0,100),
        'CambioFor' => rand(0,100),
        'VlUnitario' => rand(0,100),
        'Tarifa' => rand(0,100),
        'Taxas' => rand(0,100),
        'OutServs' => rand(0,100),
        'OutTaxas' => rand(0,100),
        'VlTotal' => rand(0,100),
        'ComisRep' => str_random(10),
        'IncentRep' => rand(0,100),
        'Sinal' => rand(0,100),
        'Saldo' => rand(0,100),
        'ComisFor' => rand(0,100),
        'IncentFor' => str_random(10),
        'VlPagar' => str_random(10),
        'SinalFor' => rand(0,100),
        'UnidCobr' => rand(0,100),
        'DifTarifa' => str_random(10),
        'Empresa' => rand(0,100),
        'LinObsRes_1a' => str_random(10),
        'LinObsRes_2a' => str_random(10),
        'LinObsRes_3a' => str_random(10),
        'TarSugeridaUnit' => rand(0,100),
        'TarNormalUnit' => rand(0,100),
        'VlCredCartao' => rand(0,100),
        'Representante' => str_random(10),
        'SiglaFor' => str_random(10),
        'EmailCentCusto' => str_random(10),
        'TarNormalTot' => rand(0,100),
        'TarSugeridaTot' => rand(0,100),
        'CodigoCli' => str_random(10),
        'CodigoFor' => str_random(10),
        'LinObsRes_4a' => str_random(10),
        'Servicos05' => str_random(10),
        'Servicos06' => str_random(10),
        'Servicos07' => str_random(10),
        'Servicos08' => str_random(10),
        'Servicos09' => str_random(10),
        'Servicos10' => str_random(10),
        'FeeCli' => str_random(10),
        'Servicos11' => str_random(10),
        'Servicos12' => str_random(10),
        'Servicos13' => str_random(10),
        'Servicos14' => str_random(10),
        'Servicos15' => str_random(10),
        'Servicos16' => str_random(10),
        'Servicos17' => str_random(10),
        'Servicos18' => str_random(10),
        'Servicos19' => str_random(10),
        'Servicos20' => str_random(10),
        'Divisao' => str_random(10),
        'Alerta_O1' => str_random(10),
        'Alerta_O2' => str_random(10),
        'Alerta_O3' => str_random(10),
        'Alerta_O4' => str_random(10),
        'Alerta_O5' => str_random(10),
        'Alerta_O6' => str_random(10),
        'Alerta_O7' => str_random(10),
        'Alerta_de_Data' => str_random(10),
        'Alerta_Tarifa_Zerada' => str_random(10),
        'Alerta_Valor_Pago' => str_random(10),
        'Alerta_Diaria' => str_random(10),
        'Alerta_Data_Entrada' => str_random(10),
        'Alerta_Data_Saida' => str_random(10),
        'Alerta_Tipo' => str_random(10),
        'Alerta_Geral' => str_random(10),
        'Diaria_Calculo' => rand(0,100),
        'lider' => str_random(10),
        'coordenador' => str_random(10),
        ]);
    
    }
}
